#!/usr/bin/env python

import sys, yaml
with open(sys.argv[1], 'r') as stream:
    try:
        h = yaml.load(stream)

        # address=/vh-1.polar.local/10.0.2.11
        print 'address=/{0}/{1}'.format(h['host_name'], h['ansible_host'])

        # ptr-record=11.2.0.10.in-addr.arpa,vh-1.polar.local
        print 'ptr-record={1}.in-addr.arpa,{0}'.format(h['host_name'], '.'.join(h['ansible_host'].split('.')[::-1]))
    except yaml.YAMLError as exc:
        print(exc)


## cmds
# for ff in host_vars/*; do ./gen-dns $ff; done
# (modify dnsmasq's conf)
# curl -ujeff:test -X PUT http://172.18.0.2:8080/restart